apiVersion: v1
kind: Namespace
metadata:
  name: speech-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speech-server
  namespace: speech-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: speech-server
  template:
    metadata:
      labels:
        name: speech-server
    spec:
      containers:
        - name: speech-server
          image: 
          imagePullPolicy: Always
          command:
            - "bash"
            - "-c"
            - "uvicorn app:app --host 0.0.0.0 --port 8080 --workers 3"
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "1"    
          envFrom:
            - secretRef:
                name: assistant-secrets
      tolerations:
        - key: "assitant-app"
          operator: "Equal"
          value: "speech-server"
          effect: "NoSchedule"
      imagePullSecrets:
        - name: acr-secret


  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---
apiVersion: v1
kind: Service
metadata:
  name: speech-server
  namespace: speech-backend

spec:
  selector:
    name: speech-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: speech-server-hpa
  namespace: speech-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: speech-server
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: "900Mi"
